import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="dark text-foreground bg-background min-h-screen">
            <main className="max-w-6xl py-unit-24 px-unit-4 mx-auto flex flex-col gap-unit-8 items-center">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
